package catdata.aql.exp;

public class MsSqlCatalog {

	public static String cql_schema = """ 	
    entities
        CHECK_CONSTRAINTS COLUMN_DOMAIN_USAGE COLUMN_PRIVILEGES COLUMNS CONSTRAINT_COLUMN_USAGE
        CONSTRAINT_TABLE_USAGE DOMAIN_CONSTRAINTS DOMAINS KEY_COLUMN_USAGE PARAMETERS
        REFERENTIAL_CONSTRAINTS ROUTINES ROUTINE_COLUMNS SCHEMATA TABLE_CONSTRAINTS
        TABLE_PRIVILEGES TABLES VIEW_COLUMN_USAGE VIEW_TABLE_USAGE VIEWS        
        
    attributes
        CONSTRAINT_CATALOG CONSTRAINT_SCHEMA CONSTRAINT_NAME CHECK_CLAUSE : CHECK_CONSTRAINTS -> Other
        DOMAIN_CATALOG DOMAIN_SCHEMA DOMAIN_NAME TABLE_CATALOG TABLE_SCHEMA TABLE_NAME COLUMN_NAME : COLUMN_DOMAIN_USAGE -> Other
        GRANTOR GRANTEE TABLE_CATALOG TABLE_SCHEMA TABLE_NAME COLUMN_NAME PRIVILEGE_TYPE IS_GRANTABLE : COLUMN_PRIVILEGES -> Other
        TABLE_CATALOG TABLE_SCHEMA TABLE_NAME COLUMN_NAME ORDINAL_POSITION COLUMN_DEFAULT IS_NULLABLE 
        DATA_TYPE CHARACTER_MAXIMUM_LENGTH CHARACTER_OCTET_LENGTH NUMERIC_PRECISION NUMERIC_PRECISION_RADIX 
        NUMERIC_SCALE DATETIME_PRECISION CHARACTER_SET_CATALOG CHARACTER_SET_SCHEMA CHARACTER_SET_NAME
        COLLATION_CATALOG COLLATION_SCHEMA COLLATION_NAME DOMAIN_CATALOG DOMAIN_SCHEMA DOMAIN_NAME : COLUMNS -> Other
        TABLE_CATALOG TABLE_SCHEMA TABLE_NAME COLUMN_NAME CONSTRAINT_CATALOG CONSTRAINT_SCHEMA 
        CONSTRAINT_NAME : CONSTRAINT_COLUMN_USAGE -> Other
        TABLE_CATALOG TABLE_SCHEMA TABLE_NAME CONSTRAINT_CATALOG CONSTRAINT_SCHEMA CONSTRAINT_NAME : CONSTRAINT_TABLE_USAGE -> Other
        CONSTRAINT_CATALOG CONSTRAINT_SCHEMA CONSTRAINT_NAME DOMAIN_CATALOG DOMAIN_SCHEMA DOMAIN_NAME 
        IS_DEFERRABLE INITIALLY_DEFERRED : DOMAIN_CONSTRAINTS -> Other
        DOMAIN_CATALOG DOMAIN_SCHEMA DOMAIN_NAME DATA_TYPE CHARACTER_MAXIMUM_LENGTH CHARACTER_OCTET_LENGTH
        COLLATION_CATALOG COLLATION_SCHEMA COLLATION_NAME CHARACTER_SET_CATALOG CHARACTER_SET_SCHEMA
        CHARACTER_SET_NAME NUMERIC_PRECISION NUMERIC_PRECISION_RADIX NUMERIC_SCALE DATETIME_PRECISION DOMAIN_DEFAULT : DOMAINS -> Other
        CONSTRAINT_CATALOG  CONSTRAINT_SCHEMA CONSTRAINT_NAME TABLE_CATALOG TABLE_SCHEMA TABLE_NAME COLUMN_NAME ORDINAL_POSITION : KEY_COLUMN_USAGE -> Other
        SPECIFIC_CATALOG SPECIFIC_SCHEMA SPECIFIC_NAME ORDINAL_POSITION PARAMETER_MODE IS_RESULT 
        AS_LOCATOR PARAMETER_NAME DATA_TYPE CHARACTER_MAXIMUM_LENGTH CHARACTER_OCTET_LENGTH
        COLLATION_CATALOG COLLATION_SCHEMA COLLATION_NAME CHARACTER_SET_CATALOG CHARACTER_SET_SCHEMA
        CHARACTER_SET_NAME NUMERIC_PRECISION NUMERIC_PRECISION_RADIX NUMERIC_SCALE 
        DATETIME_PRECISION INTERVAL_TYPE INTERVAL_PRECISION USER_DEFINED_TYPE_CATALOG
        USER_DEFINED_TYPE_SCHEMA USER_DEFINED_TYPE_NAME SCOPE_CATALOG SCOPE_SCHEMA SCOPE_NAME : PARAMETERS -> Other
    
        TABLE_CATALOG TABLE_SCHEMA TABLE_NAME TABLE_TYPE : TABLES ->  Other
        SPECIFIC_CATALOG SPECIFIC_SCHEMA SPECIFIC_NAME ROUTINE_CATALOG ROUTINE_SCHEMA ROUTINE_NAME 
        ROUTINE_TYPE MODULE_CATALOG MODULE_SCHEMA MODULE_NAME UDT_CATALOG UDT_SCHEMA UDT_NAME DATA_TYPE 
        CHARACTER_MAXIMUM_LENGTH CHARACTER_OCTET_LENGTH COLLATION_CATALOG COLLATION_SCHEMA
        COLLATION_NAME CHARACTER_SET_CATALOG CHARACTER_SET_SCHEMA CHARACTER_SET_NAME NUMERIC_PRECISION
        NUMERIC_PRECISION_RADIX NUMERIC_SCALE DATETIME_PRECISION INTERVAL_TYPE INTERVAL_PRECISION
        TYPE_UDT_CATALOG TYPE_UDT_SCHEMA TYPE_UDT_NAME SCOPE_CATALOG SCOPE_SCHEMA SCOPE_NAME MAXIMUM_CARDINALITY
        DTD_IDENTIFIER ROUTINE_BODY ROUTINE_DEFINITION EXTERNAL_NAME EXTERNAL_LANGUAGE PARAMETER_STYLE 
        IS_DETERMINISTIC SQL_DATA_ACCESS IS_NULL_CALL SQL_PATH SCHEMA_LEVEL_ROUTINE MAX_DYNAMIC_RESULT_SETS
        IS_USER_DEFINED_CAST IS_IMPLICITLY_INVOCABLE CREATED LAST_ALTERED : ROUTINES -> Other
        TABLE_CATALOG TABLE_SCHEMA TABLE_NAME COLUMN_NAME ORDINAL_POSITION COLUMN_DEFAULT IS_NULLABLE
        DATA_TYPE CHARACTER_MAXIMUM_LENGTH CHARACTER_OCTET_LENGTH NUMERIC_PRECISION NUMERIC_PRECISION_RADIX
        NUMERIC_SCALE DATETIME_PRECISION CHARACTER_SET_CATALOG CHARACTER_SET_SCHEMA CHARACTER_SET_NAME
        COLLATION_CATALOG COLLATION_SCHEMA COLLATION_NAME DOMAIN_CATALOG DOMAIN_SCHEMA DOMAIN_NAME : ROUTINE_COLUMNS -> Other
        CATALOG_NAME SCHEMA_NAME SCHEMA_OWNER DEFAULT_CHARACTER_SET_CATALOG DEFAULT_CHARACTER_SET_SCHEMA DEFAULT_CHARACTER_SET_NAME : SCHEMATA -> Other 
        CONSTRAINT_CATALOG CONSTRAINT_SCHEMA CONSTRAINT_NAME TABLE_CATALOG TABLE_SCHEMA TABLE_NAME CONSTRAINT_TYPE IS_DEFERRABLE INITIALLY_DEFERRED : TABLE_CONSTRAINTS -> Other
        GRANTOR GRANTEE TABLE_CATALOG TABLE_SCHEMA TABLE_NAME PRIVILEGE_TYPE IS_GRANTABLE : TABLE_PRIVILEGES -> Other
        VIEW_CATALOG VIEW_SCHEMA VIEW_NAME TABLE_CATALOG TABLE_SCHEMA TABLE_NAME COLUMN_NAME : VIEW_COLUMN_USAGE -> Other 
        VIEW_CATALOG VIEW_SCHEMA VIEW_NAME TABLE_CATALOG TABLE_SCHEMA TABLE_NAME : VIEW_TABLE_USAGE -> Other 
        TABLE_CATALOG TABLE_SCHEMA TABLE_NAME VIEW_DEFINITION CHECK_OPTION IS_UPDATABLE : VIEWS -> Other
         
        CONSTRAINT_CATALOG CONSTRAINT_SCHEMA CONSTRAINT_NAME UNIQUE_CONSTRAINT_CATALOG UNIQUE_CONSTRAINT_SCHEMA
        UNIQUE_CONSTRAINT_NAME MATCH_OPTION UPDATE_RULE DELETE_RULE : REFERENTIAL_CONSTRAINTS -> Other
 """;

}
